os: linux
dist: bionic
language: bash
notifications:
  email: false
script: if [[ $TRAVIS_COMMIT_MESSAGE == *"run1"* ]]; then mvn install ; fi ;
deploy:
  provider: script
  script: bash deployment1.sh
  on:
    branch: master

    
    
    
